[package]
name = "smithereens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"
nom = "7.1.3"
phf = { version = "0.11.1", features = ["macros"] }
rust_decimal = "1.29.1"
rust_decimal_macros = "1.29.1"
crepe = "0.1.8"
polars = "0.28.0"
serde = { version = "1.0.160", features = ["derive"] }
memoize = "0.4.0"
rayon = "1.7.0"
filenamify = "*"

[dev-dependencies]
insta = "1.29.0"
