[package]
name = "smithereens"
authors = ["Brooks J Rady"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
nom = "7.1.3"
phf = { version = "0.11.2", features = ["macros"] }
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
crepe = "0.1.8"
polars = "0.36.2"
serde = { version = "1.0.194", features = ["derive"] }
memoize = "0.4.2"
rayon = "1.8.0"
clap = { version = "4.4.12", features = ["derive", "cargo"] }
anyhow = "1.0.79"

[dev-dependencies]
insta = "1.34.0"
