[package]
name = "smithereens"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
nom = "7.1.3"
phf = { version = "0.11.2", features = ["macros"] }
rust_decimal = "1.33.1"
rust_decimal_macros = "1.33.1"
crepe = "0.1.8"
polars = { version = "0.35.4", default_features = false, features = ["polars-io", "csv"] }
serde = { version = "1.0.193", features = ["derive"] }
memoize = "0.4.1"
rayon = "1.8.0"
wasm-bindgen = "0.2.89"
console_error_panic_hook = "0.1.7"
cxx = "1.0.114"

[dev-dependencies]
insta = "1.34.0"

[lib]
crate-type = ["staticlib"]
