[package]
name = "wasm-shim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
muropeptide = { path = "../muropeptide" }
polychem = { path = "../polychem" }
smithereens = { path = "../smithereens" }

[lints]
workspace = true
