[package]
name = "sifter"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.49", features = ["derive"] }
csv = "1.4.0"
derive_more = { version = "2.0.1", features = ["full"] }
flate2 = { version = "1.1.4", features = ["zlib-rs"], default-features = false }
mzdata = { git = "https://github.com/mobiusklein/mzdata.git", branch="feature/avoid-double-buffer", features = ["mzml", "zlib-ng-compat"], default-features = false }
ordered-float = { version = "5.1.0", default-features = false }
thiserror = "2.0.17"

[lints]
workspace = true

[dev-dependencies]
assert_float_eq = "1.2.0"
criterion = "0.7.0"
gungraun = "0.17.0"
insta = "1.43.2"

[[bench]]
name = "c_ms2_index"
harness = false

[[bench]]
name = "g_ms2_index"
harness = false
